account/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,

    PasswordChangeView,
    PasswordChangeDoneView,
)

from account.views import (
    login_view,
    logout_view,
    register_view,
    account_verify_view,
    account_view,
    account_update_view,
    account_search_view,
    account_deactivate_view,
    account_delete_view
)


app_name = 'account'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('account_verify/<uidb64>/<token>/',
         account_verify_view, name='account-verify'),

    path('account/<user_id>/', account_view, name='account'),
    path('account_update/', account_update_view, name='account-update'),
    path('account_search/', account_search_view, name='account-search'),
    path('account_deactivate/', account_deactivate_view, name='account-deactivate'),
    path('account_delete/', account_delete_view, name='account-delete'),


    path('password_reset/', PasswordResetView.as_view(
        template_name='account/password/password_reset.html',
        email_template_name='account/password/password_reset_email.html',
        success_url=reverse_lazy('account:password-reset-done')),
        name='password-reset'
    ),
    path('password_reset_done/', PasswordResetDoneView.as_view(
        template_name='account/password/password_reset_done.html'),
        name='password-reset-done'
    ),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='account/password/password_reset_confirm.html',
        success_url=reverse_lazy('account:password-reset-complete')),
        name='password-reset-confirm'
    ),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(
        template_name='account/password/password_reset_complete.html'),
        name='password-reset-complete'
    ),

    path('password_change/', PasswordChangeView.as_view(
        template_name='account/password/password_change.html',
        success_url=reverse_lazy('account:password-change-done')),
        name='password-change'
    ),
    path('password_change_done/', PasswordChangeDoneView.as_view(
        template_name='account/password/password_change_done.html'),
        name='password-change-done'
    ),
]

basic/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='account')),
	path('', include("django_celery_tracker.urls",  namespace='celery_tracker')),
    path('api/', include('account.api.urls', namespace='account_api')),
]

handler404 = 'basic.views.page_not_found_view'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_celery_tracker/urls.py
from django.urls import path, re_path
from django_celery_tracker.views import (
    TextFormView,
    task_details,
)
app_name = "celery_tracker"
urlpatterns = [
    path("", TextFormView.as_view(), name="celery_tracker"),
    re_path('^task-details/(?P<task_id>[0-9A-Za-z\-]+)/$', task_details),
]

templates/snippets/form.html
<!-- Base form style start -->
{% csrf_token %}
{% for error in form.non_field.errors %}
<small class="text-danger">{{ error }}</small>
{% endfor %}
{% for field in form.hidden_fields %}
{{ field }}
{% for error in field.errors %}
<small class="text-danger">{{ error }}</small>
{% endfor %}
{% endfor %}
{% for field in form.visible_fields %}
<div class="form-element">
{% if field.field.widget.input_type != "file" %}
{% if field.field.widget.input_type != "checkbox" %}
<label for="{{ field.id_for_label }}">{{ field.label }}</label>
{{ field }}
{% else %}
{{ field }}
<label for="{{ field.id_for_label }}">{{ field.label }}</label>
{% endif %}
{% if field.help_text %}
<div class="ml-2 mb-0"><small>{{ field.help_text }}</small></div>
{% endif %}
{% for error in field.errors %}
<small class="text-danger">{{ error }}</small>
{% endfor %}
{% endif %}
</div>
{% endfor %}
<hr class="mt-1 mb-2">
<!-- Base form style end -->

templates/snippets/navbar.html
<!-- Navbar Start -->

<style>
.navbar {
    padding: .25rem 2.5rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
    background-color: var(--bg-primary);
    color: var(--font-color);
}

.brand-title {
    font-size: 1.75rem;
    font-weight: 700;
    padding: .25rem;
}

.brand-title a {
    text-decoration: none;
    color: var(--font-color);
    display: block;
}

.navbar-links {
    display: flex;
    justify-content: space-between;
}

.navbar-links ul {
    display: flex;
    margin: .25rem 0;
}

.navbar-links li {
    list-style: none;
	border-radius: 2px;
}

.navbar-links li a {
    text-decoration: none;
    color: var(--font-color);
    padding: .5rem 1rem;
    display: block;
}

.navbar-links li:hover {
    background-color: var(--bg-secondary);
}

.toggle-button {
    position: absolute;
    top: 1rem;
    right: 2rem;
    display: none;
    flex-direction: column;
    justify-content: space-between;
    width: 30px;
    height: 20px;
}

.toggle-button .bar {
    height: 4px;
    width: 100%;
    background-color: var(--font-color);
    border-radius: 5px;
}

.nav-input {
    width: 200px;
}

@media (max-width: 720px) {
    .toggle-button {
        display: flex;
    }

    .navbar-links {
        display: none;
        flex-direction: column;
        width: 100%;
    }

    .navbar {
        flex-direction: column;
        align-items: flex-start;
    }

    .navbar-links ul {
        width: 100%;
        flex-direction: column;
    }

    .navbar-links li {
        text-align: center;
    }

    .navbar-links li a {
        padding: .5rem 1rem;
    }

    .navbar-links.active {
        display: flex;
    }

    .nav-input {
        margin: .5rem 0;
    }
}

</style>
<nav class="navbar">
    <div class="brand-title"><a href="{% url 'celery_tracker:celery_tracker' %}">LOGO</a></div>
    <a href="#" class="toggle-button">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
    </a>
    <div class="navbar-links">
        <ul>
            <li><a href="#" id="toggle-theme">Dark Mode</a></li>
            <form class="d-flex mx-2" onsubmit="return executeQuery();">
                <input class="nav-input" type="text" placeholder="Search" name="userQuery" id="id_search">
            </form>
            {% if user.is_authenticated %}
            <li><a href="{% url 'account:account' user_id=request.user.id %}">Profile</a></li>
            <li><a href="{% url 'account:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'account:login' %}">Login</a></li>
            <li><a href="{% url 'account:register' %}">Register</a></li> 
            {% endif %}  
        </ul>
    </div>
</nav>

<script type="text/javascript">
    function executeQuery() {
        var query = ""
        query = document.getElementById('id_search').value;
        window.location.replace("{% url 'account:account-search' %}?userQuery=" + query)
        return false
    }
</script>

<script>
    const toggleBtn = document.getElementsByClassName("toggle-button")[0]
    const navbarLinks = document.getElementsByClassName("navbar-links")[0]

    toggleBtn.addEventListener("click", () => {
        navbarLinks.classList.toggle("active")
    })
</script>

<script>
    document.getElementById("toggle-theme").addEventListener("click", function(e) {
        const theme = localStorage.getItem("theme-mode")
        console.log(theme)
        if (theme === null) {
            localStorage.setItem("theme-mode", "dark")
            window.location.reload()    
        } else {
            localStorage.removeItem("theme-mode")
            window.location.reload()
        }
    })
</script>
<!-- Navbar Ends -->